version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: web-app
    container_name: web
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/app/src/
    restart: always
  